#另一種配置文件方式
server:
  port: 8080
logging:
  level:
    root: warn
    com.joe: debug


#spring-boot也可以自訂注入的資料
book:
  name: 哲學哲學雞蛋糕
  author: 哲糕
  isbn: ${random.uuid}
  description: ${book.name}的簡介很隨便，但不糟糕。
