
#這是設定指定當前活躍的配置環境(多環境配置)
#application-{自定義}.yml
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML


#spring-boot也可以自訂注入的資料
book:
  name: 哲學哲學雞蛋糕
  author: 哲糕
  isbn: ${random.uuid}
  description: ${book.name}的簡介很隨便，但不糟糕。


